services:
  db:
    image: postgres:16-alpine
    container_name: lottery-db
    restart: always
    ports:
      - "8502:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
    healthcheck:
      test: pg_isready -U postgres -d lottery
      interval: 3s
      timeout: 3s
      retries: 100
      start_period: 10s
  backend:
    image: lottery-backend
    container_name: lottery-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8501:5000"
    command: >
      sh -c "
      poetry run alembic upgrade head &&
      poetry run uvicorn api.main:app --host 0.0.0.0 --port 5000 --reload
      "
    environment:
      - APP_TITLE=くじ引きメーカー(β)
      - DB_URL=postgres:postgres@lottery-db:5432/lottery
      - FRONTEND_URL=http://localhost:8500
      - NOTICE_EMAIL=welovegamesinc+info@gmail.com
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: lottery-frontend
    container_name: lottery-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8500:5173"
    command: http-server -p 5173
    depends_on:
      - backend
