services:
  db:
    image: postgres:16-alpine
    container_name: lottery-db
    restart: always
    ports:
      - "8502:5432"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
  backend:
    image: lottery
    container_name: lottery-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: srv
    ports:
      - "8501:8501"
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 8501 --reload
    environment:
      - DB_URL=postgres:postgres@lottery-db:5432/lottery
    depends_on:
      - db
