"""empty message

Revision ID: 5a2bc86fb0ed
Revises: 6c8a4d5e9287
Create Date: 2024-06-11 16:51:53.224037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2bc86fb0ed'
down_revision: Union[str, None] = '6c8a4d5e9287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('used_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotteries', 'used_count')
    # ### end Alembic commands ###
