"""empty message

Revision ID: 66688dfabe89
Revises: e4ae7c02dda8
Create Date: 2024-06-12 21:35:24.892051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66688dfabe89'
down_revision: Union[str, None] = 'e4ae7c02dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_tokens', sa.Column('email', sa.VARCHAR(length=80), nullable=False))
    op.add_column('signup_tokens', sa.Column('account_name', sa.VARCHAR(length=24), nullable=False))
    op.add_column('signup_tokens', sa.Column('identification', sa.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signup_tokens', 'identification')
    op.drop_column('signup_tokens', 'account_name')
    op.drop_column('signup_tokens', 'email')
    # ### end Alembic commands ###
