"""empty message

Revision ID: 6e60ff2a9606
Revises: 9232a8d5b8b1
Create Date: 2024-06-11 09:47:07.126713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e60ff2a9606'
down_revision: Union[str, None] = '9232a8d5b8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pull_lottery_ids', postgresql.ARRAY(sa.INTEGER()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pull_lottery_ids')
    # ### end Alembic commands ###
