"""empty message

Revision ID: 9232a8d5b8b1
Revises: c39214f59196
Create Date: 2024-06-10 09:41:18.481888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9232a8d5b8b1'
down_revision: Union[str, None] = 'c39214f59196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('description', sa.VARCHAR(length=256), nullable=False))
    op.alter_column('lotteries', 'text',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('lotteries', 'title',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'account_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_name',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('lotteries', 'title',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('lotteries', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=False)
    op.drop_column('lotteries', 'description')
    # ### end Alembic commands ###
