"""empty message

Revision ID: 9b0dc2df1a91
Revises: c491bb061514
Create Date: 2024-06-12 18:33:37.608615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0dc2df1a91'
down_revision: Union[str, None] = 'c491bb061514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=80), nullable=False))
    op.drop_constraint('users_account_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['identification'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_account_name_key', 'users', ['account_name'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
