"""empty message

Revision ID: ab252593dc45
Revises: 
Create Date: 2024-06-13 18:33:16.248955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab252593dc45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lotteries',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=False),
    sa.Column('used_count', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signup_tokens',
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('identification', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('identification', sa.VARCHAR(length=64), nullable=False),
    sa.Column('pull_lottery_ids', postgresql.ARRAY(sa.INTEGER()), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('signup_tokens')
    op.drop_table('lotteries')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
