"""empty message

Revision ID: e4135c3ba959
Revises: c50fdbbcfb6a
Create Date: 2024-06-04 09:19:01.107936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4135c3ba959'
down_revision: Union[str, None] = 'c50fdbbcfb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_name', sa.VARCHAR(length=128), nullable=False))
    op.add_column('users', sa.Column('identification', sa.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identification')
    op.drop_column('users', 'account_name')
    # ### end Alembic commands ###
