"""empty message

Revision ID: e48945ebbeb2
Revises: 2a31a4d25d30
Create Date: 2024-06-07 10:06:52.905493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48945ebbeb2'
down_revision: Union[str, None] = '2a31a4d25d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['access_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
